"""Change name - image_credits 

Revision ID: 18bd539973e5
Revises: 7e1c254e1048
Create Date: 2023-12-07 01:41:00.571265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18bd539973e5'
down_revision = '7e1c254e1048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_and_img', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_credits', sa.TEXT(), nullable=True))
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_and_img', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', mysql.TEXT(), nullable=True))
        batch_op.drop_column('img_credits')

    # ### end Alembic commands ###
