"""Updated added image in nutrition table

Revision ID: 3a48877ed04a
Revises: 5820bc5a65b1
Create Date: 2023-12-14 05:25:24.019745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a48877ed04a'
down_revision = '5820bc5a65b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('img_credits', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.drop_column('img_credits')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
