"""Adjust for img column

Revision ID: 415e15b6c242
Revises: 18bd539973e5
Create Date: 2023-12-07 22:53:16.177274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415e15b6c242'
down_revision = '18bd539973e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_and_img', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.BLOB(),
               type_=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_and_img', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.TEXT(),
               type_=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###
