"""Updated nutrition table

Revision ID: 5820bc5a65b1
Revises: d2bb78b9adb3
Create Date: 2023-12-13 23:36:21.802359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5820bc5a65b1'
down_revision = 'd2bb78b9adb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Text(), nullable=True))
        batch_op.drop_column('datee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datee', mysql.TEXT(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
