"""Varchar for text columns

Revision ID: 7e1c254e1048
Revises: 
Create Date: 2023-12-07 01:19:18.771071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e1c254e1048'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_nutrition_info', schema=None) as batch_op:
        batch_op.alter_column('author_desc',
               existing_type=mysql.VARCHAR(length=900),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author_nutrition_info', schema=None) as batch_op:
        batch_op.alter_column('author_desc',
               existing_type=sa.VARCHAR(length=500),
               type_=mysql.VARCHAR(length=900),
               existing_nullable=False)

    # ### end Alembic commands ###
