"""Add nutrition table

Revision ID: b6d3fcd8f975
Revises: 415e15b6c242
Create Date: 2023-12-13 22:07:17.473338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d3fcd8f975'
down_revision = '415e15b6c242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), nullable=False),
    sa.Column('header', sa.VARCHAR(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrition')
    # ### end Alembic commands ###
