"""Update nutrition table

Revision ID: d2bb78b9adb3
Revises: b6d3fcd8f975
Create Date: 2023-12-13 23:35:41.016174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bb78b9adb3'
down_revision = 'b6d3fcd8f975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datee', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition', schema=None) as batch_op:
        batch_op.drop_column('datee')

    # ### end Alembic commands ###
