"""Delete unused tables

Revision ID: eceba52b3751
Revises: fd731ab2bb50
Create Date: 2023-12-20 12:53:23.604346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eceba52b3751'
down_revision = 'fd731ab2bb50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_nutrition_info')
    op.drop_table('facts_about_pigs')
    op.drop_table('main_nutrition_info')
    op.drop_table('author_nutrition_info')
    op.drop_table('nutrition')
    op.drop_table('types_of_pigs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types_of_pigs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=1500), nullable=False),
    sa.Column('a', mysql.VARCHAR(length=1500), nullable=False),
    sa.Column('img_url', mysql.VARCHAR(length=1500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nutrition',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('header', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('desc', mysql.TEXT(), nullable=False),
    sa.Column('source', mysql.TEXT(), nullable=True),
    sa.Column('date', mysql.TEXT(), nullable=True),
    sa.Column('img', mysql.TEXT(), nullable=True),
    sa.Column('img_credits', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('author_nutrition_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('author_desc', mysql.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('main_nutrition_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('header', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('desc', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('facts_about_pigs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sub_nutrition_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sub_header', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('sub_desc', mysql.VARCHAR(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
